### ISSUE TITLE
malformed cellIndex in sheet xml file when column count is larger than 26

### ISSUE THREAD

**Issue by edward-mzj** [jiteshkumawat/oxml.js#1]
in line 580:
                           var columnChar = String.fromCharCode(65 + columnIndex);
                            var value = this._sheet.values[rowIndex][columnIndex];
                            var cellIndex = columnChar + (rowIndex + 1);
  malformed cellIndex in xml:
<c r="Z2" ...
<c r="[2" ...
...
<c r="a2" ...
<c r="b2" ...

**Comment by jiteshkumawat** [comment]
> in line 580:
> var columnChar = String.fromCharCode(65 + columnIndex);
> var value = this._sheet.values[rowIndex][columnIndex];
> var cellIndex = columnChar + (rowIndex + 1);
> malformed cellIndex in xml:
> <c r="Z2" ...
> <c r="[2" ...
> ...
> <c r="a2" ...
> <c r="b2" ...

Noted. Thanks for reporting this. Will cater this in next push. Although have shifted the development to JOI:
https://github.com/jiteshkumawat/joi
