### ISSUE TITLE
Correct content-type for excel download

### ISSUE THREAD

**Issue by iholgado** [jiteshkumawat/oxml.js#5]
Every time you download a generated excel with this library in Firefox, a popup will open with this option: "open with 7-zip manager" . This is because the download file has application/zip as mime-type.

I suggest change the line 32 with the following code:

compressedFile.saveFile = function (fileName, callback) {
return zip.generateAsync({ type: "blob" **, mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"** })
                .then(function (content) {
                    try {

**Comment by jiteshkumawat** [comment]
Thanks for pointing it out. Done.
